### ISSUE TITLE
Need a html front-end static page. 

### ISSUE THREAD

**Issue by spil3141** [spil3141/siteX#1]
Must Have : 
1. Search section
2. Signup Button
3. Login Button 
Currently, I have an incomplete version  in /siteX/siteX_1.0/Blog/templates/html/index.html

**Comment by JS-goose** [comment]
I see that you self assigned, but if you're still looking for help on this I'd be glad to take a crack at it.

Are you looking for any particular styling or just something simple you can hook up to a back end?

**Comment by spil3141** [comment]
Hi , thanks for responding.
anything will do.
im quite new to the project management features on github so i might have done something wrong, concerning me self assigning, i did that unknowingly.I will correct it now .

**Comment by JS-goose** [comment]
No worries at all, I'll start working on this and have something built in a jiffy 😃

**Comment by spil3141** [comment]
Awesome ! 👍 
So my play is :
	1. Design and Code the Database  -> Completed 
	2. Design and Code the front-End -> Not Yet 
        3. Combine the Back-end and Front-end  -> Not yet 

# i need to Figure out how to get input from the site input tag to the database.
